# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caegory',
            new_name='category',
        ),
    ]
